[package]
name = "rust_part5"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = {version = "1.5.7", features = ["derive"]}
borsh-derive = "1.5.7"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
